---
# tasks file for codedeploy
- name: Download CodeDeploy Agent
  get_url:
    url: "https://aws-codedeploy-eu-west-1.s3.amazonaws.com/latest/install"
    dest: /tmp/codedeploy-install
    mode: 0755

- name: Codedeploy Install
  become: true
  command: /tmp/codedeploy-install auto
